---
- name: Run database updates.
  command: drush updatedb -y
  args:
    chdir: "{{ drupal_core_path }}"

# TODO: Import configuration if configured?
# TODO: Other commands if configured?

- name: Rebuild Drupal caches.
  command: drush cache-rebuild --quiet
  args:
    chdir: "{{ drupal_core_path }}"
